### ISSUE TITLE
question

### ISSUE THREAD

**Issue by lz233149** [hadipourh/zeroplus#1]
Hello, may I ask if the method you provided can perform 23 rounds of impossible differential attacks on CARFT? How to modify it? Thank you

**Comment by hadipourh** [comment]
Hello,

Thanks for your question!
It may produce a 23-round attack. However, there might be a small gap between the actual time complexity and the time complexity estimated by the tool. Therefore, after deriving an output from the tool, a few manual verifications might be necessary to ensure that the attack works and that the time complexity is below that of an exhaustive search.
We have only confirmed the 21-round attack in our paper.
